#自动赋值
 person:
  name: "Tony"
  age: ${random.int}  #随机生成数字
  happy: false
  birth: 2020/12/28
  maps: {k1: v1, k2: v2}
  hello: happy
  lists:
    - code
    - music
    - girls
  dog:
    name: ${person.hello:hello}_旺财  #类似于三目运算符
    age: 4